# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.

# Include the standard Flutter lint rules
include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    unused_import: ignore  # Suppress unused imports warning globally if necessary
  exclude:
    - lib/*.g.dart           # Exclude generated Dart files (e.g., JSON serializers)
    - lib/**/*.g.dart        # Exclude any deeply nested generated Dart files
    - lib/generated/**       # Exclude generated files from protobufs or other tools
    - android/               # Exclude Android directory from analysis
    - ios/                   # Exclude iOS directory from analysis
  language:
    strict-casts: false      # Disable strict casts to avoid issues in dynamic JSON data
    strict-inference: false   # Disable strict inference for JSON factory constructors
    strict-raw-types: false   # Disable strict raw types for flexibility in JSON handling

linter:
  rules:
    # Adjust the following rules based on preferences for coding style:
    prefer_single_quotes: true              # Enforce single quotes for consistency
    prefer_relative_imports: true           # Use relative imports within the project
    require_trailing_commas: true           # Enable trailing commas for readability
    avoid_dynamic_calls: false              # Disable to avoid errors with dynamic JSON data
    avoid_renaming_method_parameters: false # Allow renaming parameters in factory constructors
    avoid_private_typedef_functions: false  # Useful for generated code with private typedefs
    always_specify_types: false             # Disable if specifying types causes issues with dynamic data
    avoid_null_checks_in_equality_operators: false # Avoid issues with nullable data

# Additional comments:
# - The strict language options were set to `false` for JSON flexibility.
# - Generated files are excluded to prevent lint errors from affecting generated code.
